### ISSUE TITLE
Replace search entry with "Gtk::SearchEntry"

### ISSUE THREAD

**Issue by SlouchyButton** [duzda/deadbeef-filebrowser-reborn#16]
As in title, this is a specific (badly documented) GTK element for search. It automatically adds remove all button when there is text in it. This is a quick and easy way to remove any current filters (search) and show everything again.
Even tho it is not greatly documented, it should from my experience be a drop-in replacement for normal Entry.

**Comment by duzda** [comment]
![image](https://user-images.githubusercontent.com/25201406/215854448-f75cffb7-9d5e-4462-bb9f-924008615ade.png)
Might've been already implemented?

**Comment by SlouchyButton** [comment]
My bad, have mistaken my fork with main repo and had wrong version installed.
