### ISSUE TITLE
cannot choose plugin in deadbeef

### ISSUE THREAD

**Issue by brainbow1** [duzda/deadbeef-filebrowser-reborn#17]
Hello!

Till now I used the original filebrowser-plugin, but when I

I added the plugin to ~/.local/lib/deadbeef
but it doesnt load....

I get the following terminal output:

loading plugin /home/debian-desktop/.local/lib/deadbeef/ddb_misc_filebrowser_reborn.so
dlopen error: libboost_serialization.so.1.74.0: Cannot open the shared object file: File or directory not found
trying /home/debian-desktop/.local/lib/deadbeef/ddb_misc_filebrowser_reborn.fallback.so...
plugin ddb_misc_filebrowser_reborn.so not found or failed to load 

Can you please let me know how to fix this?
I appreciate your answer and your work on this plugin <3

**Comment by brainbow1** [comment]
I installed libboost-all-dev, which contains that libboost_serialization.so.1.74.0.
So this error message is gone. Now the next error message:

loading plugin /home/debian-desktop/.local/lib/deadbeef/ddb_misc_filebrowser_reborn.so
dlopen error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/debian-desktop/.local/lib/deadbeef/ddb_misc_filebrowser_reborn.so)
trying /home/debian-desktop/.local/lib/deadbeef/ddb_misc_filebrowser_reborn.fallback.so...
plugin ddb_misc_filebrowser_reborn.so not found or failed to load 

I looked in my system and in debian repos and found that I have

libc-2.31.so in my system, located under /lib/x86_64-linux-gnu

But according to the error message in terminal it seems that libc-2.33.so is needed. 

I cant find that file anywhere in the debian repositories in any package....
Do u think there is a way of finding a solution for that problem? 

My system:
OS: Debian GNU/Linux 11 (bullseye) x86_64 
Kernel: 6.0.0-0.deb11.6-amd64 
DE: Xfce 4.16

**Comment by duzda** [comment]
Hello, 

I think you have just a few options, although I do not have any Debian experience.

1) You have to build the binaries by yourself, this should hopefully be easy, especially if the names of Debian's packages are the same as Ubuntu's.

Download the source code of the project, either via git

`
git clone https://github.com/duzda/deadbeef-filebrowser-reborn.git
`

or by pressing the code button and download zip on github page.

Then make sure you have all the required dependecies:

`
apt install libtag1-dev libboost-all-dev libgtkmm-3.0-dev ninja-build meson gcc`

and then from project root folder (` cd deadbeef-filebrowser-reborn`):

`
meson build --buildtype release && cd build && ninja && ../quick-install.sh`

2) I might rebuild the project with static linked dependencies, not sure whether it would help though.

3) You can download glibc 2.36 from unstable repos, just have to add them. There's plenty of resources on how to this available, just put something along the lines of "debian install package from unstable" into Google. But be vary, as this may fuck your system up, hopefully not, since glibc shouldn't have any dependencies, but it still may happen.

 Please just try the 1st option and reach back, feel free to ask if any of the provided instructions are unclear or you simply can't build the project by youself.

**Comment by brainbow1** [comment]
thanks a lot for ur answer! I tried the first option which was sadly not very succesfull over here :(

`~/deadbeef-filebrowser-reborn$ meson build --buildtype release && cd build && ninja && ../quick-install.sh
The Meson build system
Version: 0.56.2
Source dir: /home/debian-desktop/deadbeef-filebrowser-reborn
Build dir: /home/debian-desktop/deadbeef-filebrowser-reborn/build
Build type: native build
Project name: filebrowser
Project version: 0.5.0
C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
C linker for the host machine: cc ld.bfd 2.35.2
C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
C++ linker for the host machine: c++ ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency gtkmm-3.0 found: YES 3.24.2
Run-time dependency taglib found: YES 1.11.1
Run-time dependency threads found: YES
Run-time dependency Boost (found: serialization) found: YES 1.74.0 (/usr)
Build targets in project: 1

Found ninja-1.10.1 at /usr/bin/ninja
[1/31] Compiling C++ object src/libddb_misc_filebrowser_reborn.so.p/plugin.cpp.o
FAILED: src/libddb_misc_filebrowser_reborn.so.p/plugin.cpp.o 
c++ -Isrc/libddb_misc_filebrowser_reborn.so.p -Isrc -I../src -I../include -I../include/cache -I../include/cache/covers -I../include/cache/covers/implementation -I../include/cache/treemodel -I../include/gui -I../include/gui/views -I../include/plugin -I../include/metadata -I../include/metadata/abstract -I../include/metadata/implementation -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/taglib -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -fPIC -DBOOST_ALL_NO_LIB -pthread -DVMAJOR=0 -DVMINOR=5 -MD -MQ src/libddb_misc_filebrowser_reborn.so.p/plugin.cpp.o -MF src/libddb_misc_filebrowser_reborn.so.p/plugin.cpp.o.d -o src/libddb_misc_filebrowser_reborn.so.p/plugin.cpp.o -c ../src/plugin.cpp
In file included from ../src/plugin.cpp:1:
../include/plugin.hpp:3:10: fatal error: deadbeef/deadbeef.h: Datei oder Verzeichnis nicht gefunden
    3 | #include "deadbeef/deadbeef.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[2/31] Compiling C++ object src/libddb...ebrowser_reborn.so.p/cache_utils.cpp.o
FAILED: src/libddb_misc_filebrowser_reborn.so.p/cache_utils.cpp.o 
c++ -Isrc/libddb_misc_filebrowser_reborn.so.p -Isrc -I../src -I../include -I../include/cache -I../include/cache/covers -I../include/cache/covers/implementation -I../include/cache/treemodel -I../include/gui -I../include/gui/views -I../include/plugin -I../include/metadata -I../include/metadata/abstract -I../include/metadata/implementation -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/taglib -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -fPIC -DBOOST_ALL_NO_LIB -pthread -DVMAJOR=0 -DVMINOR=5 -MD -MQ src/libddb_misc_filebrowser_reborn.so.p/cache_utils.cpp.o -MF src/libddb_misc_filebrowser_reborn.so.p/cache_utils.cpp.o.d -o src/libddb_misc_filebrowser_reborn.so.p/cache_utils.cpp.o -c ../src/cache/utils.cpp
In file included from ../src/cache/utils.cpp:3:
../include/plugin.hpp:3:10: fatal error: deadbeef/deadbeef.h: Datei oder Verzeichnis nicht gefunden
    3 | #include "deadbeef/deadbeef.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[3/31] Compiling C++ object src/libddb...reborn.so.p/gui_dispatcherbridge.cpp.o
FAILED: src/libddb_misc_filebrowser_reborn.so.p/gui_dispatcherbridge.cpp.o 
c++ -Isrc/libddb_misc_filebrowser_reborn.so.p -Isrc -I../src -I../include -I../include/cache -I../include/cache/covers -I../include/cache/covers/implementation -I../include/cache/treemodel -I../include/gui -I../include/gui/views -I../include/plugin -I../include/metadata -I../include/metadata/abstract -I../include/metadata/implementation -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/taglib -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -fPIC -DBOOST_ALL_NO_LIB -pthread -DVMAJOR=0 -DVMINOR=5 -MD -MQ src/libddb_misc_filebrowser_reborn.so.p/gui_dispatcherbridge.cpp.o -MF src/libddb_misc_filebrowser_reborn.so.p/gui_dispatcherbridge.cpp.o.d -o src/libddb_misc_filebrowser_reborn.so.p/gui_dispatcherbridge.cpp.o -c ../src/gui/dispatcherbridge.cpp
In file included from ../include/gui/fbtreemodel.hpp:16,
                 from ../src/gui/dispatcherbridge.cpp:6:
../include/plugin.hpp:3:10: fatal error: deadbeef/deadbeef.h: Datei oder Verzeichnis nicht gefunden
    3 | #include "deadbeef/deadbeef.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[4/31] Compiling C++ object src/libddb...rowser_reborn.so.p/gui_container.cpp.o
FAILED: src/libddb_misc_filebrowser_reborn.so.p/gui_container.cpp.o 
c++ -Isrc/libddb_misc_filebrowser_reborn.so.p -Isrc -I../src -I../include -I../include/cache -I../include/cache/covers -I../include/cache/covers/implementation -I../include/cache/treemodel -I../include/gui -I../include/gui/views -I../include/plugin -I../include/metadata -I../include/metadata/abstract -I../include/metadata/implementation -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/taglib -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -fPIC -DBOOST_ALL_NO_LIB -pthread -DVMAJOR=0 -DVMINOR=5 -MD -MQ src/libddb_misc_filebrowser_reborn.so.p/gui_container.cpp.o -MF src/libddb_misc_filebrowser_reborn.so.p/gui_container.cpp.o.d -o src/libddb_misc_filebrowser_reborn.so.p/gui_container.cpp.o -c ../src/gui/container.cpp
In file included from ../include/gui/fbtreemodel.hpp:16,
                 from ../src/gui/container.cpp:3:
../include/plugin.hpp:3:10: fatal error: deadbeef/deadbeef.h: Datei oder Verzeichnis nicht gefunden
    3 | #include "deadbeef/deadbeef.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[5/31] Compiling C++ object src/libddb...owser_reborn.so.p/gui_addressbox.cpp.o
FAILED: src/libddb_misc_filebrowser_reborn.so.p/gui_addressbox.cpp.o 
c++ -Isrc/libddb_misc_filebrowser_reborn.so.p -Isrc -I../src -I../include -I../include/cache -I../include/cache/covers -I../include/cache/covers/implementation -I../include/cache/treemodel -I../include/gui -I../include/gui/views -I../include/plugin -I../include/metadata -I../include/metadata/abstract -I../include/metadata/implementation -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/taglib -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -fPIC -DBOOST_ALL_NO_LIB -pthread -DVMAJOR=0 -DVMINOR=5 -MD -MQ src/libddb_misc_filebrowser_reborn.so.p/gui_addressbox.cpp.o -MF src/libddb_misc_filebrowser_reborn.so.p/gui_addressbox.cpp.o.d -o src/libddb_misc_filebrowser_reborn.so.p/gui_addressbox.cpp.o -c ../src/gui/addressbox.cpp
In file included from ../include/gui/fbtreemodel.hpp:16,
                 from ../src/gui/addressbox.cpp:6:
../include/plugin.hpp:3:10: fatal error: deadbeef/deadbeef.h: Datei oder Verzeichnis nicht gefunden
    3 | #include "deadbeef/deadbeef.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[6/31] Compiling C++ object src/libddb....so.p/cache_treemodel_serializer.cpp.o
FAILED: src/libddb_misc_filebrowser_reborn.so.p/cache_treemodel_serializer.cpp.o 
c++ -Isrc/libddb_misc_filebrowser_reborn.so.p -Isrc -I../src -I../include -I../include/cache -I../include/cache/covers -I../include/cache/covers/implementation -I../include/cache/treemodel -I../include/gui -I../include/gui/views -I../include/plugin -I../include/metadata -I../include/metadata/abstract -I../include/metadata/implementation -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/taglib -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -fPIC -DBOOST_ALL_NO_LIB -pthread -DVMAJOR=0 -DVMINOR=5 -MD -MQ src/libddb_misc_filebrowser_reborn.so.p/cache_treemodel_serializer.cpp.o -MF src/libddb_misc_filebrowser_reborn.so.p/cache_treemodel_serializer.cpp.o.d -o src/libddb_misc_filebrowser_reborn.so.p/cache_treemodel_serializer.cpp.o -c ../src/cache/treemodel/serializer.cpp
In file included from ../include/gui/fbtreemodel.hpp:16,
                 from ../include/cache/treemodel/serializer.hpp:5,
                 from ../src/cache/treemodel/serializer.cpp:1:
../include/plugin.hpp:3:10: fatal error: deadbeef/deadbeef.h: Datei oder Verzeichnis nicht gefunden
    3 | #include "deadbeef/deadbeef.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[7/31] Compiling C++ object src/libddb..._reborn.so.p/gui_modelserializer.cpp.o
FAILED: src/libddb_misc_filebrowser_reborn.so.p/gui_modelserializer.cpp.o 
c++ -Isrc/libddb_misc_filebrowser_reborn.so.p -Isrc -I../src -I../include -I../include/cache -I../include/cache/covers -I../include/cache/covers/implementation -I../include/cache/treemodel -I../include/gui -I../include/gui/views -I../include/plugin -I../include/metadata -I../include/metadata/abstract -I../include/metadata/implementation -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/taglib -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -fPIC -DBOOST_ALL_NO_LIB -pthread -DVMAJOR=0 -DVMINOR=5 -MD -MQ src/libddb_misc_filebrowser_reborn.so.p/gui_modelserializer.cpp.o -MF src/libddb_misc_filebrowser_reborn.so.p/gui_modelserializer.cpp.o.d -o src/libddb_misc_filebrowser_reborn.so.p/gui_modelserializer.cpp.o -c ../src/gui/modelserializer.cpp
In file included from ../include/gui/fbtreemodel.hpp:16,
                 from ../src/gui/modelserializer.cpp:1:
../include/plugin.hpp:3:10: fatal error: deadbeef/deadbeef.h: Datei oder Verzeichnis nicht gefunden
    3 | #include "deadbeef/deadbeef.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[8/31] Compiling C++ object src/libddb...wser_reborn.so.p/gui_fbtreemodel.cpp.o
FAILED: src/libddb_misc_filebrowser_reborn.so.p/gui_fbtreemodel.cpp.o 
c++ -Isrc/libddb_misc_filebrowser_reborn.so.p -Isrc -I../src -I../include -I../include/cache -I../include/cache/covers -I../include/cache/covers/implementation -I../include/cache/treemodel -I../include/gui -I../include/gui/views -I../include/plugin -I../include/metadata -I../include/metadata/abstract -I../include/metadata/implementation -I/usr/include/gtkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/x86_64-linux-gnu/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/x86_64-linux-gnu/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/x86_64-linux-gnu/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/taglib -I/usr/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++17 -O3 -fPIC -DBOOST_ALL_NO_LIB -pthread -DVMAJOR=0 -DVMINOR=5 -MD -MQ src/libddb_misc_filebrowser_reborn.so.p/gui_fbtreemodel.cpp.o -MF src/libddb_misc_filebrowser_reborn.so.p/gui_fbtreemodel.cpp.o.d -o src/libddb_misc_filebrowser_reborn.so.p/gui_fbtreemodel.cpp.o -c ../src/gui/fbtreemodel.cpp
In file included from ../include/gui/fbtreemodel.hpp:16,
                 from ../src/gui/fbtreemodel.cpp:1:
../include/plugin.hpp:3:10: fatal error: deadbeef/deadbeef.h: Datei oder Verzeichnis nicht gefunden
    3 | #include "deadbeef/deadbeef.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[18/31] Compiling C++ object src/libdd...covers_implementation_coverfirst.cpp.o
ninja: build stopped: subcommand failed.
`

It seems like its quite complicated..
At the moment I am very limited in time as well as very limited in risk-loving :-) thats why I think its best for me to accept that option 1 just not works over here... don't want to mess with packages from unstable etc... too much risk for me as Im not that experienced and if I mess anything up I am unable to make it work again most of the times :)
Maybe u know how to solve the compilation issues with option 1... otherwise its okay as well...
thank you a lot for ur help!

**Comment by brainbow1** [comment]
update:
It seems like the original filebrowser plugin is working now without any crashes, as I'm using GTK3 now and deactivated the "use cache" option in the "waveform seekbar"-plugin.
I think any effort is unneccessary as long as it works.... :-)
thank u anyway for ur help and for ur work with this plugin... probably debian is too conservative :-)

**Comment by duzda** [comment]
Seems like the only issue is missing deadbeef headers, you can check whether files deadbeef.h, gtkui_api.h exists in your /usr/include/deadbeef folder, if not, that is a problem. These files should be installed on your system along with deadbeef. 
You can also use `find . -name "deadbeef.h"` 

The output of this command should be a location to your headers, you can then simply change the path in src/meson.build on line 11, to the output of this command (such as /usr/lib/...).

If you do not have the headers (they should come preinstalled with deadbeef though), you can grab new headers from https://sourceforge.net/projects/deadbeef/files/staticdeps/ddb-headers-latest.tar.bz2/download and simply put them into /usr/include/deadbeef/

**Comment by duzda** [comment]
Of course feel free to use the old plugin as long as it works! :)

**Comment by duzda** [comment]
Feel free to reopen if it becomes relevant once again.
