### ISSUE TITLE
terminate called after throwing an instance of 'Gdk::PixbufError'

### ISSUE THREAD

**Issue by daemonspudguy** [duzda/deadbeef-filebrowser-reborn#18]
I don't know what that error means, but the plugin throws it and then DeaDBeeF promptly crashes with an IOT instruction (core dumped) status.

**Comment by duzda** [comment]
Hello, 

can you give a few hints, such as when this happens, what have you been doing, was it like this always or just recently, after some change? This is most likely linked to the cover art, it may either be a corrupted .png/.jpeg in a folder or incorrect retrieval from metadata, but it's a wild guess, details are much appreciated. Deleting ~/.cache/deadbeef/filebrowser might be enough in case your cache got somehow corrupted (the plugin should however notice if it's corrupted).

**Comment by daemonspudguy** [comment]
Just recently, and it happened after I added a new folder to my library. The original Filebrowser plugin works, as well.

**Comment by daemonspudguy** [comment]
I got it working again. I had to set it to only look at metadata, because something about searching for covers in the folders is breaking it, for some reason.

**Comment by duzda** [comment]
Nevermind, I think I know what's the problem. Thanks for reporting!

**Comment by daemonspudguy** [comment]
> Would you be able to somehow (probably via cloud) provide the cover file from the new folder?

No, because it doesn't have one.

**Comment by duzda** [comment]
I've tried some fixes, hopefully they should work, feel free to try the [pre-release](https://github.com/duzda/deadbeef-filebrowser-reborn/releases/tag/v0.6.0). The app shouldn't crash, if you open log, either in app or via running deadbeef from terminal, now there should be warnings about any corrupted icon.

**Comment by daemonspudguy** [comment]
That works!
