### ISSUE TITLE
Crash while loading files into tree view

### ISSUE THREAD

**Issue by SlouchyButton** [duzda/deadbeef-filebrowser-reborn#2]
The plugin sometimes crashes the player while loading folder structure. This always happens in default home folder (probably because very big nested structure) and sometimes in Music folder containing 17k files and 980 folders with at most level 2 nesting (in 1/3 of cases). Had to change the folder manually in settings file for deadbeef to "unbrick" player.

There is no error nor exception in terminal, couldn't debug further *yet*.

**Comment by SlouchyButton** [comment]
Rewriting to use MVC via Gtk::TreeModel seems to solve it, just need few tweaks to polish it up and clean the code.

**Comment by duzda** [comment]
> The plugin sometimes crashes the player while loading folder structure. This always happens in default home folder (probably because very big nested structure) and sometimes in Music folder containing 17k files and 980 folders with at most level 2 nesting (in 1/3 of cases). Had to change the folder manually in settings file for deadbeef to "unbrick" player.
> 
> There is no error nor exception in terminal, couldn't debug further _yet_.

Home directory most likely crashes because of the loops in filesystem caused by wine.

**Comment by duzda** [comment]
> Rewriting to use MVC via Gtk::TreeModel seems to solve it, just need few tweaks to polish it up and clean the code.

The problem is most likely this function ``` TreeFilebrowser::threadedRefreshTree ```, as ``` self->mTreeView->thaw_notify(); ``` is getting called once all files are registered to be uploaded to the model, instead the thaw->notify() should be called once we have really uploaded the last row. This probably means that ``` TreeFilebrowser::fillRow ``` has to know whether it's the last row or not, and if it's then it should wake the tree.
