### ISSUE TITLE
Bookmark folders

### ISSUE THREAD

**Issue by Rin247** [duzda/deadbeef-filebrowser-reborn#21]
Would it be possible to implement such a feature? I keep all my music on a second drive divided by even more folders. Meaning every time I open up deadbeef I have to browse for said folder. I understand that we can never have a proper indexed database like with foobar because linux is linux (i.e forever fragmented). But the default location should be possible to edit at least right?

**Comment by duzda** [comment]
Hello,

the default location after startup can be changed in the settings. I'm not sure how would I go about implementing bookmarks, but as of right now, you can simply create master folder with links to other locations and set default path to this master folder.

If you want indexed database, this project is not what you want, you can checkout fork of this project, called [deadbeef-media-library](https://github.com/SlouchyButton/deadbeef-media-library), which does provide this feature.
