### ISSUE TITLE
Caching model

### ISSUE THREAD

**Issue by SlouchyButton** [duzda/deadbeef-filebrowser-reborn#8]
Discuss whether caching files could or should be implemented to prevent long startup of deadbeef.

If we always cache and always target hitting the cache without TTL, it might create unexpected behavior for users - expecting current state of folder from "file browser".

We could experiment whether modifying files in a folder changes the date modified of the folder itself - we could then compare these dates to check whether we should do full refresh or not. If this worked, we could then even implement it for "Go!" button and only forcefully refresh when user clicks refresh.

Also as an idea, this unexpected behavior could be more self-explanatory if we added a refresh button next to "Go!" button, so users would naturally click it when something would seem to be missing.

**Comment by duzda** [comment]
We could experiment whether modifying files in a folder changes the date modified of the folder itself -> Yes it does, just beware, your file explorer probably caches metadata.
